CREATE TABLE judge_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(512),
    auth_mode VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ
);

CREATE TABLE problem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    statement VARCHAR(1600) NOT NULL,
    sample_input VARCHAR(1200) NOT NULL,
    sample_output VARCHAR(1200) NOT NULL,
    difficulty VARCHAR(255) NOT NULL
);

CREATE TABLE test_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL REFERENCES problem(id),
    input_data VARCHAR(2000) NOT NULL,
    expected_output VARCHAR(2000) NOT NULL,
    hidden BOOLEAN NOT NULL
);

CREATE TABLE submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    problem_id BIGINT NOT NULL REFERENCES problem(id),
    language VARCHAR(255) NOT NULL,
    source_code VARCHAR(10000) NOT NULL,
    state VARCHAR(255) NOT NULL,
    verdict VARCHAR(255) NOT NULL,
    stdout VARCHAR(4000),
    stderr VARCHAR(4000),
    runtime_ms BIGINT NOT NULL,
    memory_mb INTEGER NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE INDEX idx_test_case_problem_id ON test_case(problem_id);
CREATE INDEX idx_submission_problem_id ON submission(problem_id);
CREATE INDEX idx_submission_user_id ON submission(user_id);
CREATE INDEX idx_submission_created_at ON submission(created_at DESC);
CREATE INDEX idx_submission_state ON submission(state);
CREATE INDEX idx_submission_verdict ON submission(verdict);
